#!/usr/bin/env python3
"""
SBMO validation — A-Box builder (stdlib only).

Reads the raw Google Forms export and emits an ANONYMIZED A-Box in Turtle that
owl:imports the canonical T-Box (sbmo.rdf is never modified). Each survey case
becomes one sbmo:SoftwareBusinessModel individual with per-case value
individuals for every selected controlled-vocabulary value.

Modeling choices:
  - Per-case value individuals (ex:CaseNN_ClassName) keep the cross-dimensional
    links (exhibitsNetworkEffect, mitigates) scoped to each case and avoid any
    conflation or disjointness conflict between cases.
  - exhibitsNetworkEffect links the case EcosystemRole individual(s) to the case
    NetworkEffectType individual(s), per the T-Box domain/range.
  - mitigates links each case MitigationStrategy to the case's
    ImplementationChallenge individuals (case-level mitigation->challenge).
  - All 31 cases are instantiated; completeness against the 7 mandatory
    properties is reported (not used to drop cases).

ANONYMITY: no company/product/respondent identifiers are written. Only safe
data properties are asserted: hasLaunchYear (gYear) and hasBillingPeriodicity
(normalized category).

Layout: this script lives in sbmo/validation/scripts/. It reads the private
raw CSV from ../../../validations/sbmo-form-answers.csv (sibling of the sbmo
repo, never committed) and writes the anonymized A-Box to
sbmo/validation/protege/sbmo-validation-abox.ttl.

Usage:  python3 build_abox.py [path/to/sbmo-form-answers.csv]
"""

import csv
import os
import re
import sys

import sbmo_mapping as M

HERE = os.path.dirname(os.path.abspath(__file__))
VALIDATION_ROOT = os.path.dirname(HERE)  # sbmo/validation
SBMO_ROOT = os.path.dirname(VALIDATION_ROOT)  # sbmo
DISSERTATION_ROOT = os.path.dirname(SBMO_ROOT)  # sibling of sbmo, validations
DEFAULT_RAW = os.path.join(DISSERTATION_ROOT, "validations", "sbmo-form-answers.csv")
RAW = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_RAW
OUT = os.path.join(VALIDATION_ROOT, "protege", "sbmo-validation-abox.ttl")

COL_YEAR, COL_PERIODICITY = 5, 18
ABOX_NS = "https://rafaelc-rb.github.io/sbmo/abox#"
ABOX_ONT = "https://rafaelc-rb.github.io/sbmo/abox"

MANDATORY = ["product_type", "delivery", "revenue", "pricing",
             "customer", "ecosystem", "channel"]


def norm_periodicity(raw: str) -> str:
    s = raw.strip().lower()
    if not s:
        return ""
    if any(k in s for k in ("não há", "nao ha", "não possui", "sem faturamento", "não tem receita")):
        return "None"
    has_m, has_a = "mensal" in s or "mens8" in s, "anual" in s
    has_t = "transaç" in s or "transac" in s
    others = sum(k in s for k in ("semanal", "semestral", "trimestr", "unitária", "unitaria", "diário", "diario", "overnight"))
    kinds = sum([has_m, has_a, has_t]) + others
    if kinds >= 3 or (others and (has_m or has_a)):
        return "Mixed"
    if has_m and has_a:
        return "Monthly or annual"
    if has_m:
        return "Monthly"
    if has_a:
        return "Annual"
    if has_t:
        return "Per transaction"
    if "trimestr" in s:
        return "Quarterly"
    return "Other"


def year_literal(raw: str):
    m = re.search(r"(19|20)\d{2}", raw)
    return m.group(0) if m else None


def ind(case: str, cls: str) -> str:
    return f"ex:{case}_{cls}"


def main():
    with open(RAW, encoding="utf-8") as f:
        rows = list(csv.reader(f))
    data = rows[1:]
    n = len(data)
    cases = [f"Case{str(i + 1).zfill(2)}" for i in range(n)]

    out = []
    out.append("# SBMO validation A-Box (anonymized). Generated by build_abox.py -- do not edit by hand.")
    out.append("# Imports the canonical T-Box; sbmo.rdf is never modified.")
    out.append("@prefix sbmo: <https://rafaelc-rb.github.io/sbmo#> .")
    out.append(f"@prefix ex: <{ABOX_NS}> .")
    out.append("@prefix owl: <http://www.w3.org/2002/07/owl#> .")
    out.append("@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .")
    out.append("@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .")
    out.append("")
    out.append(f"<{ABOX_ONT}> a owl:Ontology ;")
    out.append("    owl:imports <https://rafaelc-rb.github.io/sbmo> .")
    out.append("")

    incomplete = {}
    value_inds = []  # (iri_local, class) to declare types

    for i, c in enumerate(cases):
        r = data[i]
        # map every dimension
        sel = {}
        for dim in M.DIMENSIONS:
            cell = r[dim["col"]] if dim["col"] < len(r) else ""
            mapped, _, _ = M.map_cell(dim, cell)
            # dedupe, keep order
            seen, uniq = set(), []
            for x in mapped:
                if x not in seen:
                    seen.add(x); uniq.append(x)
            sel[dim["key"]] = uniq

        missing = [k for k in MANDATORY if not sel[k]]
        if missing:
            incomplete[c] = missing

        # ---- SBM individual + data properties ----
        triples = [f"ex:{c} a sbmo:SoftwareBusinessModel"]
        yr = year_literal(r[COL_YEAR] if COL_YEAR < len(r) else "")
        if yr:
            triples.append(f'sbmo:hasLaunchYear "{yr}"^^xsd:gYear')
        per = norm_periodicity(r[COL_PERIODICITY] if COL_PERIODICITY < len(r) else "")
        if per:
            triples.append(f'sbmo:hasBillingPeriodicity "{per}"')

        # ---- object properties to per-case value individuals ----
        for dim in M.DIMENSIONS:
            key = dim["key"]
            if key in ("network_effect", "mitigation"):
                continue  # handled specially below
            for cls in sel[key]:
                triples.append(f"sbmo:{dim['prop']} {ind(c, cls)}")
                value_inds.append((f"{c}_{cls}", cls))

        out.append(" ;\n    ".join(triples) + " .")

        # ---- network effect: EcosystemRole -> NetworkEffectType ----
        for ne in sel["network_effect"]:
            value_inds.append((f"{c}_{ne}", ne))
            for eco in sel["ecosystem"]:
                out.append(f"{ind(c, eco)} sbmo:exhibitsNetworkEffect {ind(c, ne)} .")

        # ---- mitigation: MitigationStrategy -> ImplementationChallenge ----
        for mit in sel["mitigation"]:
            value_inds.append((f"{c}_{mit}", mit))
            mtri = [f"{ind(c, mit)} a sbmo:{mit}"]
            for ch in sel["challenge"]:
                mtri.append(f"sbmo:mitigates {ind(c, ch)}")
            out.append(" ;\n    ".join(mtri) + " .")
        out.append("")

    # ---- declare types for all value individuals (dedup) ----
    out.append("# ---- value individuals (typed by their SBMO leaf class) ----")
    declared = set()
    for local, cls in value_inds:
        if local in declared:
            continue
        declared.add(local)
        out.append(f"ex:{local} a sbmo:{cls} .")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")

    print(f"Wrote {OUT}")
    print(f"Cases instantiated: {n}  | value individuals: {len(declared)}")
    print(f"Complete cases (all 7 mandatory): {n - len(incomplete)}  | incomplete: {len(incomplete)}")
    for c, miss in incomplete.items():
        print(f"    {c} missing: {miss}")


if __name__ == "__main__":
    main()
