#!/usr/bin/env python3
"""
SBMO validation — dissertation assets for the socio-demographic profile and
statistical analysis sections of Chapter 7 (Ontology Evaluation).

Reads the ANONYMIZED, already-aggregated outputs of:
  - reproduce_sbmo_analysis_fixed.r  (sbmo_analysis_output/*.csv)
  - extract_respondent_role.py       (survey-derived/respondent_role_categories.csv)
and writes ready-to-input LaTeX table/tikz fragments into
dissertation-paper/assets/ontology_evaluation/{tables,tikz}/.

No raw identifying data is read here; every input is already an anonymized,
aggregate CSV (see the two scripts above for the anonymity handling).

Usage: python3 generate_dissertation_assets.py
"""

import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))
STATS_OUT = os.path.join(HERE, "sbmo_analysis_output")
VALIDATION_ROOT = os.path.dirname(os.path.dirname(HERE))  # sbmo/validation
SURVEY_DERIVED = os.path.join(VALIDATION_ROOT, "survey-derived")
SBMO_ROOT = os.path.dirname(VALIDATION_ROOT)
DISSERTATION_ROOT = os.path.dirname(SBMO_ROOT)
ASSETS = os.path.join(DISSERTATION_ROOT, "dissertation-paper", "assets", "ontology_evaluation")
TABLES = os.path.join(ASSETS, "tables")
TIKZ = os.path.join(ASSETS, "tikz")
os.makedirs(TABLES, exist_ok=True)
os.makedirs(TIKZ, exist_ok=True)

GENERATED_HEADER = (
    "% Generated by sbmo/validation/scripts/statistical_analysis/"
    "generate_dissertation_assets.py -- do not edit by hand.\n"
)


def read_csv(path):
    with open(path, encoding="utf-8") as f:
        return list(csv.DictReader(f))


def tex_escape(s):
    """Escape LaTeX special characters in a label pulled from data/category
    names (e.g. "Product & Design" -> "Product \\& Design"). Without this,
    an unescaped '&' inside a pgfplots yticklabels list is parsed as a
    misplaced alignment tab and breaks the build."""
    return (s.replace("\\", r"\textbackslash{}")
             .replace("&", r"\&").replace("%", r"\%")
             .replace("_", r"\_").replace("#", r"\#"))


# ---------------------------------------------------------------------------
# 1. Respondent role category chart (socio-demographic profile)
# ---------------------------------------------------------------------------
def role_chart():
    rows = read_csv(os.path.join(SURVEY_DERIVED, "respondent_role_categories.csv"))
    n = len(rows)
    order = ["Engineering", "Leadership", "Product & Design", "Founder",
             "Technical Advisory", "Other / Analyst"]
    counts = {c: 0 for c in order}
    for r in rows:
        counts[r["respondent_role_category"]] += 1

    # ybar-inverted style (xbar), largest at top, matching revenue_sources.tex conventions
    ordered = sorted(order, key=lambda c: counts[c])  # ascending, since y dir will be reversed by listing order
    lines = []
    for i, cat in enumerate(ordered, start=1):
        pct = 100 * counts[cat] / n
        lines.append(f"{pct:.1f} {i} {counts[cat]}")
    yticklabels = ",".join("{%s}" % tex_escape(c) for c in ordered)

    tex = GENERATED_HEADER + f"""\\begin{{tikzpicture}}
\\begin{{axis}}[
    xbar,
    bar width=6pt,
    ytick=data,
    axis y line*=none,
    axis x line*=bottom,
    x tick label style={{font=\\scriptsize}},
    y tick label style={{font=\\scriptsize}},
    label style={{font=\\scriptsize}},
    xlabel={{Percentage of respondents (\\%)}},
    xmin=0,
    xmax={max(100 * v / n for v in counts.values()) + 20:.0f},
    width=0.85\\columnwidth,
    height=5cm,
    yticklabels={{{yticklabels}}},
    y=7mm,
    enlarge y limits={{abs=0.5}},
    nodes near coords,
    nodes near coords align=horizontal,
    every node near coord/.append style={{
        black, font=\\scriptsize, text opacity=1,
        fill=white, fill opacity=0.6, outer sep=\\pgflinewidth
    }},
    visualization depends on={{\\thisrow{{n}} \\as \\mycount}},
    nodes near coords={{\\pgfmathprintnumber\\pgfplotspointmeta\\% (n=\\pgfmathprintnumber[fixed,precision=0]{{\\mycount}})}}
]
\\addplot[pattern color=hardblue, pattern=north east lines] table [x=perc, y=idx, meta=perc] {{
perc idx n
""" + "\n".join(lines) + """
};
\\end{axis}
\\end{tikzpicture}
"""
    with open(os.path.join(TIKZ, "respondent_roles.tex"), "w", encoding="utf-8") as f:
        f.write(tex)
    return counts, n


# ---------------------------------------------------------------------------
# 2. Knowledge self-assessment score chart (socio-demographic profile)
# ---------------------------------------------------------------------------
def knowledge_chart():
    rows = read_csv(os.path.join(STATS_OUT, "processed_data.csv"))
    scores = [r["KnowledgeScore"] for r in rows
              if r["KnowledgeScore"] and r["KnowledgeScore"] != "NA"]
    n = len(scores)
    counts = {str(s): 0 for s in range(1, 6)}
    for s in scores:
        counts[s] = counts.get(s, 0) + 1

    lines = []
    for i, score in enumerate(["1", "2", "3", "4", "5"], start=1):
        c = counts.get(score, 0)
        pct = 100 * c / n if n else 0
        lines.append(f"{pct:.1f} {i} {c}")

    tex = GENERATED_HEADER + f"""\\begin{{tikzpicture}}
\\begin{{axis}}[
    ybar,
    bar width=14pt,
    ymin=0,
    ymax={max(100 * counts.get(s, 0) / n for s in ["1","2","3","4","5"]) + 20:.0f},
    ylabel={{Percentage of respondents (\\%)}},
    xlabel={{Self-assessed knowledge (1 = low, 5 = high)}},
    symbolic x coords={{1,2,3,4,5}},
    xtick=data,
    x tick label style={{font=\\scriptsize}},
    y tick label style={{font=\\scriptsize}},
    label style={{font=\\scriptsize}},
    width=0.75\\columnwidth,
    height=5cm,
    nodes near coords,
    every node near coord/.append style={{font=\\scriptsize}},
    ymajorgrids=true,
    grid style={{gray!20}}
]
\\addplot[pattern color=hardblue, pattern=north east lines] coordinates {{
""" + " ".join(f"({s},{100*counts.get(s,0)/n:.1f})" for s in ["1","2","3","4","5"]) + """
};
\\end{axis}
\\end{tikzpicture}
"""
    with open(os.path.join(TIKZ, "knowledge_score.tex"), "w", encoding="utf-8") as f:
        f.write(tex)
    return counts, n


# ---------------------------------------------------------------------------
# 2b. Operational status chart (task 5: replace prose-only reporting with a
#     chart, per advisor feedback "só tem tabela")
# ---------------------------------------------------------------------------
STATUS_LABEL = {"Sim": "Operational", "Parcialmente": "Partially operational", "Não": "Planning stage"}
STATUS_ORDER = ["Sim", "Parcialmente", "Não"]


def operational_status_chart():
    rows = {r["Status"]: r for r in read_csv(os.path.join(STATS_OUT, "operational_status.csv"))}
    n = sum(int(rows[s]["n"]) for s in STATUS_ORDER)
    lines = []
    for i, status in enumerate(STATUS_ORDER, start=1):
        c = int(rows[status]["n"])
        pct = 100 * c / n
        lines.append(f"{pct:.1f} {i} {c}")
    yticklabels = ",".join("{%s}" % tex_escape(STATUS_LABEL[s]) for s in STATUS_ORDER)

    tex = GENERATED_HEADER + f"""\\begin{{tikzpicture}}
\\begin{{axis}}[
    xbar,
    bar width=16pt,
    ytick=data,
    axis y line*=none,
    axis x line*=bottom,
    x tick label style={{font=\\scriptsize}},
    y tick label style={{font=\\scriptsize}},
    label style={{font=\\scriptsize}},
    xlabel={{Percentage of cases (\\%)}},
    xmin=0, xmax=90,
    width=0.75\\columnwidth,
    height=3.6cm,
    yticklabels={{{yticklabels}}},
    y=9mm,
    enlarge y limits={{abs=0.6}},
    nodes near coords,
    nodes near coords align=horizontal,
    every node near coord/.append style={{
        black, font=\\scriptsize, text opacity=1,
        fill=white, fill opacity=0.6, outer sep=\\pgflinewidth
    }},
    visualization depends on={{\\thisrow{{n}} \\as \\mycount}},
    nodes near coords={{\\pgfmathprintnumber\\pgfplotspointmeta\\% (n=\\pgfmathprintnumber[fixed,precision=0]{{\\mycount}})}}
]
\\addplot[pattern color=hardblue, pattern=north east lines] table [x=perc, y=idx, meta=perc] {{
perc idx n
""" + "\n".join(lines) + """
};
\\end{axis}
\\end{tikzpicture}
"""
    with open(os.path.join(TIKZ, "operational_status.tex"), "w", encoding="utf-8") as f:
        f.write(tex)


# ---------------------------------------------------------------------------
# 2c. Controlled-vocabulary coverage chart (task 5: complements the existing
#     assets/ontology/tables/coverage.tex table with a visual comparison)
# ---------------------------------------------------------------------------
def coverage_chart():
    rows = read_csv(os.path.join(STATS_OUT, "coverage.csv"))
    # Preserve the same dimension order as assets/ontology/tables/coverage.tex.
    order = ["Product/service type", "Delivery mode", "Revenue source", "Pricing strategy",
             "Customer type", "Ecosystem role", "Acquisition channel", "IP regime",
             "Pricing base unit", "Network effect", "Success factor",
             "Implementation challenge", "Mitigation strategy"]
    by_dim = {r["Dimension"]: r for r in rows}
    lines = []
    for i, dim in enumerate(reversed(order), start=1):
        cov = 100 * float(by_dim[dim]["Coverage"])
        lines.append(f"{cov:.1f} {i}")
    yticklabels = ",".join("{%s}" % tex_escape(d) for d in reversed(order))

    tex = GENERATED_HEADER + f"""\\begin{{tikzpicture}}
\\begin{{axis}}[
    xbar,
    bar width=7pt,
    ytick=data,
    axis y line*=none,
    axis x line*=bottom,
    x tick label style={{font=\\scriptsize}},
    y tick label style={{font=\\scriptsize}},
    label style={{font=\\scriptsize}},
    xlabel={{Controlled-vocabulary coverage (\\%)}},
    xmin=75, xmax=105,
    width=0.85\\columnwidth,
    height=10cm,
    yticklabels={{{yticklabels}}},
    y=7mm,
    enlarge y limits={{abs=0.5}},
    nodes near coords,
    every node near coord/.append style={{font=\\scriptsize}}
]
\\addplot[pattern color=hardblue, pattern=north east lines] table [x=cov, y=idx] {{
cov idx
""" + "\n".join(lines) + """
};
\\end{axis}
\\end{tikzpicture}
"""
    with open(os.path.join(TIKZ, "coverage.tex"), "w", encoding="utf-8") as f:
        f.write(tex)


# ---------------------------------------------------------------------------
# 3. RV coefficient chart + table (statistical analysis)
# ---------------------------------------------------------------------------
DIM_LABEL = {  # dimension_columns keys are already English in the R script
    "Revenue source": "Revenue source", "Delivery mode": "Delivery mode",
    "Pricing strategy": "Pricing strategy", "Customer type": "Customer type",
    "Acquisition channel": "Acquisition channel", "Ecosystem role": "Ecosystem role",
    "Network effect": "Network effect", "Success factor": "Success factor",
    "Implementation challenge": "Implementation challenge",
    "Mitigation strategy": "Mitigation strategy",
}


def fmt_p(p):
    p = float(p)
    return "$<0.001$" if p < 0.001 else f"{p:.3f}"


def rv_assets():
    rows = read_csv(os.path.join(STATS_OUT, "rv_associations.csv"))
    lines_chart = []
    table_rows = []
    for i, r in enumerate(rows, start=1):
        rv = float(r["RV"])
        cq = r["CQ"]
        a, b = DIM_LABEL[r["DimensionA"]], DIM_LABEL[r["DimensionB"]]
        lines_chart.append(f"{rv:.3f} {i} {cq}")
        table_rows.append(
            f"{cq} & {a} $\\times$ {b} & {rv:.3f} & {fmt_p(r['PermutationP'])} & {fmt_p(r['BH_q'])} \\\\"
        )
    yticklabels = ",".join("{%s}" % tex_escape(r["CQ"]) for r in rows)

    chart = GENERATED_HEADER + f"""\\begin{{tikzpicture}}
\\begin{{axis}}[
    xbar,
    bar width=10pt,
    ytick=data,
    axis y line*=none,
    axis x line*=bottom,
    x tick label style={{font=\\scriptsize}},
    y tick label style={{font=\\scriptsize}},
    label style={{font=\\scriptsize}},
    xlabel={{RV coefficient}},
    xmin=0, xmax=0.65,
    width=0.75\\columnwidth,
    height=5cm,
    yticklabels={{{yticklabels}}},
    y dir=reverse,
    y=7mm,
    enlarge y limits={{abs=0.5}},
    nodes near coords,
    every node near coord/.append style={{font=\\scriptsize}}
]
\\addplot[pattern color=hardblue, pattern=north east lines] table [x=rv, y=idx] {{
rv idx
""" + "\n".join(f"{l.split()[0]} {l.split()[1]}" for l in lines_chart) + """
};
\\end{axis}
\\end{tikzpicture}
"""
    with open(os.path.join(TIKZ, "rv_associations.tex"), "w", encoding="utf-8") as f:
        f.write(chart)

    table = GENERATED_HEADER + """\\begin{table}[!htb]
\\renewcommand{\\arraystretch}{1.3}
\\caption{Multivariate association (RV coefficient) between the dimension pairs underlying CQ1--CQ6, with permutation-test $p$-values and Benjamini--Hochberg-adjusted $q$-values (9,999 permutations, 6 hypotheses).}
\\label{tab:rv_associations}
\\centering
\\small
\\begin{tabular}{l|l|r|r|r}
    \\bottomrule
    \\rowcolor{gray!50}
    \\textbf{CQ} & \\textbf{Dimension pair} & \\textbf{RV} & \\textbf{$p_{perm}$} & \\textbf{$q_{BH}$} \\\\
    \\hline
""" + "\n    ".join(table_rows) + """
    \\toprule
\\end{tabular}
\\end{table}
"""
    with open(os.path.join(TABLES, "rv_associations.tex"), "w", encoding="utf-8") as f:
        f.write(table)
    return rows


# ---------------------------------------------------------------------------
# 4. Strongest binary pair per CQ (phi / Fisher) table
# ---------------------------------------------------------------------------
# Hand-verified mapping from the raw Portuguese option label (base, before the
# first parenthesis) to the English class label already used elsewhere in the
# dissertation (assets/ontology/tables/frequencies.tex), so the vocabulary
# stays consistent across tables.
PT_TO_EN_BASE = {
    "Receita por suporte": "Support",
    "Entrega híbrida": "Hybrid",
    "Precificação por assinatura": "Subscription pricing",
    "Receita por assinatura": "Subscription",
    "B2C": "B2C",
    "Crescimento liderado pelo produto": "Product-led growth",
    "Plataforma bilateral": "Two-sided platform",
    "Efeito de rede cruzado": "Cross-side",
    "Gestão do ecossistema": "Ecosystem management",
    "Disrupção do ecossistema de parceiros": "Partner disruption",
    "Adoção de modelo híbrido": "Hybrid model",
    "Transformação de fluxo de receita": "Revenue-model transition",
}


def base(label):
    return label.split(" (", 1)[0].strip()


def phi_table():
    rows = read_csv(os.path.join(STATS_OUT, "strongest_binary_pairs.csv"))
    table_rows = []
    for r in rows:
        a = PT_TO_EN_BASE[base(r["OptionA"])]
        b = PT_TO_EN_BASE[base(r["OptionB"])]
        phi = float(r["Phi"])
        p = float(r["FisherP"])
        table_rows.append(f"{r['CQ']} & {a} $\\leftrightarrow$ {b} & {phi:.3f} & {fmt_p(p)} \\\\")

    table = GENERATED_HEADER + """\\begin{table}[!htb]
\\renewcommand{\\arraystretch}{1.3}
\\caption{Strongest binary association ($\\phi$ coefficient) within each competency-question pair, restricted to options selected in at least 3 and at most 28 cases; $p$-values from Fisher's exact test. Descriptive (options selected from the observed data), not independent confirmatory tests.}
\\label{tab:phi_pairs}
\\centering
\\small
\\begin{tabular}{l|l|r|r}
    \\bottomrule
    \\rowcolor{gray!50}
    \\textbf{CQ} & \\textbf{Option pair} & \\textbf{$\\phi$} & \\textbf{$p$ (Fisher)} \\\\
    \\hline
""" + "\n    ".join(table_rows) + """
    \\toprule
\\end{tabular}
\\end{table}
"""
    with open(os.path.join(TABLES, "phi_pairs.tex"), "w", encoding="utf-8") as f:
        f.write(table)
    return rows


# ---------------------------------------------------------------------------
# 5. Sensitivity analysis table
# ---------------------------------------------------------------------------
def sensitivity_table():
    full = {r["CQ"]: r for r in read_csv(os.path.join(STATS_OUT, "rv_associations.csv"))}
    sens = read_csv(os.path.join(STATS_OUT, "sensitivity_analysis.csv"))
    table_rows = []
    for r in sens:
        cq = r["CQ"]
        table_rows.append(
            f"{cq} & {float(full[cq]['RV']):.3f} & {fmt_p(full[cq]['PermutationP'])} & "
            f"{float(r['RV']):.3f} & {fmt_p(r['PermutationP'])} \\\\"
        )
    table = GENERATED_HEADER + """\\begin{table}[!htb]
\\renewcommand{\\arraystretch}{1.3}
\\caption{Sensitivity analysis: RV coefficients recomputed after retaining a single response per identified organization ($n=27$), compared with the full sample ($n=31$).}
\\label{tab:sensitivity}
\\centering
\\small
\\begin{tabular}{l|rr|rr}
    \\bottomrule
    \\rowcolor{gray!50}
     & \\multicolumn{2}{c|}{\\textbf{All cases ($n=31$)}} & \\multicolumn{2}{c}{\\textbf{Sensitivity ($n=27$)}} \\\\
    \\textbf{CQ} & \\textbf{RV} & \\textbf{$p_{perm}$} & \\textbf{RV} & \\textbf{$p_{perm}$} \\\\
    \\hline
""" + "\n    ".join(table_rows) + """
    \\toprule
\\end{tabular}
\\end{table}
"""
    with open(os.path.join(TABLES, "sensitivity.tex"), "w", encoding="utf-8") as f:
        f.write(table)


if __name__ == "__main__":
    role_counts, role_n = role_chart()
    know_counts, know_n = knowledge_chart()
    operational_status_chart()
    coverage_chart()
    rv_rows = rv_assets()
    phi_rows = phi_table()
    sensitivity_table()
    print(f"Wrote assets to {TABLES} and {TIKZ}")
    print("Role categories:", role_counts, "n=", role_n)
    print("Knowledge scores:", know_counts, "n=", know_n)
